### PR TITLE
Added statd host argument

### PR DESCRIPTION
**Pull request by andrecloutier-pd**

### CODE REVIEW

**Review by theckman — CHANGES_REQUESTED** [review]
Can you please rebase this against my fork and open the PR there? I'd be more than happy to review it and cut a new release with it in it.

I've still been unable to get a commitment from PagerDuty to properly maintain this project. I'm worried this change won't get merged, and even if it does that a release won't be cut. I'm not even sure there's anyone still at PD who wants to maintain cronner.

**Comment by theckman** [comment]
Unless this PR is inherently that commitment from PagerDuty...

**Comment by theckman** [comment]
Also, I'd suggest not bumping the version in this PR. Instead I would merge this without the version change, and then increase the version to `0.3.0` in a separate change.

Version releases should be disjointed from feature additions.

**Comment by theckman** [comment]
@andrecloutier-pd thank you so much.

If you'd be interested in contributing your change, I'd love to have it in my version of `cronner`. I was thinking of doing this very recently as well, and would much-prefer the original author get the credit they deserve.

If you don't have time to contribute to the forked repo, I'd be more-than-happy to cherry-pick the change while ensuring you retain authorship for the feature.

**Comment by andrecloutier-pd** [comment]
No worries. I'll send a PR your way either today or early next week. 👍

**Pull request merged**
